// The 55 communication theories from the AURA Lab theory explorer.
//
// Vendored as a reduced dataset (src/data/theories.min.json, regenerated by
// scripts/sync-theories.mjs) so the picker can filter offline. The explorer at
// /theories/ is the authority and every theory here deep-links back to it.
//
// This exists because "what theory did they use?" was a free-text box, which
// meant the lab's own theory dataset and the tool that most needed it never
// spoke to each other. A student typing "uses and gratifications" from memory
// is not choosing a lens; they are recalling the one lens they remember.

import data from '../data/theories.min.json'

export interface Theory {
  slug: string
  name: string
  aka?: string[]
  categories: string[]
  summary: string
  key_terms?: string[]
  originator?: string
  year?: string
  related?: string[]
}

export const THEORIES = data as Theory[]

export const THEORY_CATEGORIES: string[] = [...new Set(THEORIES.flatMap((t) => t.categories))].sort()

export function theoryUrl(slug: string): string {
  return `https://aura-lab.siue.edu/theories/${slug}/`
}

export function findTheory(nameOrSlug: string): Theory | null {
  const v = nameOrSlug.trim().toLowerCase()
  if (!v) return null
  return (
    THEORIES.find((t) => t.slug === v) ??
    THEORIES.find((t) => t.name.toLowerCase() === v) ??
    THEORIES.find((t) => (t.aka ?? []).some((a) => a.toLowerCase() === v)) ??
    null
  )
}

/** Name, alternative names, key terms and summary all count as a match. */
export function searchTheories(query: string, category: string | null): Theory[] {
  const q = query.trim().toLowerCase()
  let out = THEORIES
  if (category) out = out.filter((t) => t.categories.includes(category))
  if (!q) return out
  const scored = out
    .map((t) => {
      const name = t.name.toLowerCase()
      const aka = (t.aka ?? []).join(' ').toLowerCase()
      const terms = (t.key_terms ?? []).join(' ').toLowerCase()
      const summary = t.summary.toLowerCase()
      let score = 0
      if (name.startsWith(q)) score = 100
      else if (name.includes(q)) score = 80
      else if (aka.includes(q)) score = 70
      else if (terms.includes(q)) score = 50
      else if (summary.includes(q)) score = 30
      return { t, score }
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || a.t.name.localeCompare(b.t.name))
  return scored.map((x) => x.t)
}

/** Theories the explorer itself links to this one, for trying a second lens. */
export function relatedTo(slug: string): Theory[] {
  const t = findTheory(slug)
  if (!t?.related) return []
  return t.related.map((s) => findTheory(s)).filter((x): x is Theory => Boolean(x))
}
